# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b85b8b1ec7913a157d2e6b095322fe1f5e10260dad73e503a3c9f59939de6481f811dd635f0da8817135097cd23e437fb4fc6aa0d2e68b8700fbd4cc87eb55e8

test:
  secret_key_base: 892f79eeff310f7c17493db8c21d0ae0afcff29c9c2867eaa8363dfc32db3b2863811907804dcfff52c96f22c96ccc720e51ba407dabf887068e92705296aae8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
